app:
  auth:
    jwt-secret: "replace-with-very-long-secret-key-at-least-32-chars"
    access-ttl-seconds: 900
    refresh-ttl-seconds: 1209600
  gamification:
    recommended-esg-threshold: 70

    trip:
      co2-kg-per-passenger-km: 0.12
      esg-per-completed-trip: 2

    waste:
      grams-per-coin: 100
      esg-per-deposit: 1
      plastic-co2-kg-per-kg: 1.5
      paper-co2-kg-per-kg: 0.9
      glass-co2-kg-per-kg: 0.3
      battery-co2-kg-per-kg: 2.0
      max-weight-per-deposit-grams: 5000
      max-daily-approved-weight-grams: 20000
      alert-threshold-percentage: 90
server:
  port: 65535
spring: #application in dev mode
  datasource: #datasource
    url: jdbc:postgresql://localhost:5432/kbtu_green_ecosystem #url for docker container's database
    username: green_user
    password: green_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #checking database without change
    show-sql: true #SQL logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway: #for migrations
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true